"""Queries only. Never commits -- the service owns the transaction.

The in-flight authorisation state is not duplicated here: `google_oauth_states` serves
both the Gmail and the Drive flow (see `GoogleOAuthState.purpose`), and
`GmailRepository.add_state`/`consume_state` already implement the one-statement,
race-safe redemption that a second copy of the same logic could only get wrong by
drifting from it. This repository owns the one table that is Drive's alone.
"""

from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from pigrocrm.core.actor import ADMIN_ROLES
from pigrocrm.core.auth.models import User
from pigrocrm.core.drive.models import GoogleDriveAccount


class DriveRepository:
    def __init__(self, session: Session) -> None:
        self.session = session

    def account_for_user(self, user_id: UUID) -> GoogleDriveAccount | None:
        return self.session.execute(
            select(GoogleDriveAccount).where(GoogleDriveAccount.user_id == user_id)
        ).scalar_one_or_none()

    def storage_account(self) -> GoogleDriveAccount | None:
        """The account whose credential may write generated documents, or `None`.

        Three conditions, and all are refusals rather than filters. The owner is an
        admin *now* (REB-457): `users.ruolo` is joined at every call, never remembered,
        so a demoted admin stops supplying the space's storage at the next operation.
        The write folder receives every document the space generates, so it is the
        space's setting, and only an admin may choose it (`set_roots` refuses the field
        from anyone else). A collaboratore's row may still hold a folder, set over REST
        before that refusal existed or left from a time they were admin; it is not a
        candidate, so their roots-only save (which bumps `updated_at`) cannot redirect
        the space's documents, and their disconnect cannot break them.

        `status == 'active'`: a revoked, expired or disconnected grant cannot write, and
        answering with one would turn a fixable settings problem into a Google error
        three requests deep.
        `storage_folder_id IS NOT NULL`: connected is not configured -- a Drive with no
        chosen folder must never be written into, because the only alternative would be
        picking a folder somewhere in somebody's personal Drive on their behalf.

        No `user_id`, unlike `account_for_user`: this is not somebody's Drive, it is
        *the installation's* place to put documents. A document generated by an
        automation, or uploaded by a collaborator who has no Google account of their
        own, is written with the titolare's credential -- so the question this answers
        has no actor in it, only the owner's current role.

        `scalar_one_or_none` is deliberately not used, and `LIMIT 1` is not a
        micro-optimisation. The installation is single-tenant and `user_id` is unique,
        so more than one qualifying row is not the expected state -- but it is reachable
        (two users each connect a Drive and each choose a folder), and a query that
        raised `MultipleResultsFound` there would take every upload and every download
        down with it. The most recently updated row is the answer instead: it is the one
        somebody most recently chose.

        `id` breaks the tie after `updated_at`, and it is not decoration: `updated_at`
        is a timestamp two rows can genuinely share (two accounts configured inside the
        same transaction, or inside the same clock tick), and with `LIMIT 1` over an
        ambiguous ordering Postgres is free to return either one -- possibly a different
        one on the next call, which would mean two consecutive uploads landing in two
        different folders with nothing in the code to explain it. The ids here are
        UUIDv7, so the tie-break is itself chronological rather than arbitrary.
        """
        return self.session.execute(
            select(GoogleDriveAccount)
            .join(User, User.id == GoogleDriveAccount.user_id)
            .where(
                GoogleDriveAccount.status == "active",
                GoogleDriveAccount.storage_folder_id.is_not(None),
                User.ruolo.in_(ADMIN_ROLES),
            )
            .order_by(GoogleDriveAccount.updated_at.desc(), GoogleDriveAccount.id.desc())
            .limit(1)
        ).scalar_one_or_none()

    def add(self, account: GoogleDriveAccount) -> GoogleDriveAccount:
        self.session.add(account)
        self.session.flush()
        return account
